### ISSUE TITLE
MySQL command failed upon login

### ISSUE THREAD

**Issue by huomio** [Marco-Peter/TaikoBot#32]
Illuminate  \  Database  \  QueryException  PHP 8.1.27 10.34.2
![TaikoZuerich_Login-Failure_20240316](https://github.com/Marco-Peter/TaikoBot/assets/160257930/022ca9df-143f-45aa-a8b7-0c802810953b)

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql failed: Name or service not known

select * from `sessions` where `id` = XmmwNQk01DGrxthbqgpVmFPIXakNd3hw7mJKX99X limit 1

**Comment by huomio** [comment]
upon login php spits this error message at me
greez daniel.

**Comment by Marco-Peter** [comment]
Did this just happen?
I was just uploading a new version, so you might have caught a bad moment ;-)
Can you try again and maybe clear the browser cache?

**Comment by huomio** [comment]
I caught the perfect moment 😁

Now it's working flawlessly.

Thanks & tara d.

**Comment by Marco-Peter** [comment]
Wonderful :-)
Thanks for the feedback
